package models;

// Generated 28-ene-2015 11:14:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Habilidad generated by hbm2java
 */
public class Habilidad implements java.io.Serializable {

	private int id;
	private String denominacion;
	private Set pokemons = new HashSet(0);

	public Habilidad() {
	}

	public Habilidad(int id) {
		this.id = id;
	}

	public Habilidad(int id, String denominacion, Set pokemons) {
		this.id = id;
		this.denominacion = denominacion;
		this.pokemons = pokemons;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	public Set getPokemons() {
		return this.pokemons;
	}

	public void setPokemons(Set pokemons) {
		this.pokemons = pokemons;
	}

}
