package models;

// Generated 28-ene-2015 11:14:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tipo generated by hbm2java
 */
public class Tipo implements java.io.Serializable {

	private int id;
	private String denominacion;
	private Set pokedexesForTipo2 = new HashSet(0);
	private Set pokedexesForTipo = new HashSet(0);

	public Tipo() {
	}

	public Tipo(int id) {
		this.id = id;
	}

	public Tipo(int id, String denominacion, Set pokedexesForTipo2,
			Set pokedexesForTipo) {
		this.id = id;
		this.denominacion = denominacion;
		this.pokedexesForTipo2 = pokedexesForTipo2;
		this.pokedexesForTipo = pokedexesForTipo;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	public Set getPokedexesForTipo2() {
		return this.pokedexesForTipo2;
	}

	public void setPokedexesForTipo2(Set pokedexesForTipo2) {
		this.pokedexesForTipo2 = pokedexesForTipo2;
	}

	public Set getPokedexesForTipo() {
		return this.pokedexesForTipo;
	}

	public void setPokedexesForTipo(Set pokedexesForTipo) {
		this.pokedexesForTipo = pokedexesForTipo;
	}

}
